# This is a basic workflow to help you get started with Actions

name: Initiate repository

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      customer:
        type: string
        description: Customer
        required: true
      project:
        type: string
        description: Project
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 3.1.x
          
      - name: Generate project
        run: dotnet new webapi --name ${{ github.event.inputs.customer }}.${{ github.event.inputs.project }}
       
      - name: Generate test project
        run: dotnet new xunit --name ${{ github.event.inputs.customer }}.${{ github.event.inputs.project }}.UnitTests
      
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v2.9
